# this is compose file for the prod
services:
  backend:
    build: backend/
    # image: ghcr.io/kar1mov-u/study_hub_backend:latest

    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_started
    networks:
      - studyhub_net
    env_file:
      - .env
    ports:
      - "8080:8080"

  db:
    image: postgres:latest
    env_file:
      - .env

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      
    ports:
      - "5432:5432"
    networks:
      - studyhub_net
    volumes:
      - study_hub_db_test:/var/lib/postgresql


  migrate:
    build: ./migrations 
    # image: ghcr.io/kar1mov-u/study_hub-migrate:latest
    networks:
      - studyhub_net
    depends_on:
      db:
        condition: service_healthy
    command:
       - -path=/migrations/
       - -database=postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:5432/${DB_NAME}?sslmode=disable
       - up


  frontend:
    build: frontend/
    # image: ghcr.io/kar1mov-u/study_hub_front_end:latest

    ports:
      - "80:80" 
    networks:
      - studyhub_net
    depends_on:
      backend:
        condition: service_started
    
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - studyhub_net
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/mnesia

volumes:
  study_hub_db_test:
  rabbitmq_data:


networks:
  studyhub_net:
    driver: bridge
